{% set version = '0.0.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jcolors
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jcolors_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jcolors/jcolors_{{ version }}.tar.gz
  sha256: 26e686e30571682a637087af05ed7829b708eacf2ad33785efe183c83293b5a1

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-scales
  run:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-scales

test:
  commands:
    - $R -e "library('jcolors')"           # [not win]
    - "\"%R%\" -e \"library('jcolors')\""  # [win]

about:
  home: https://jaredhuling.github.io/jcolors/
  license: GPL-2
  summary: Contains a selection of color palettes and 'ggplot2' themes designed by the package
    author.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: jcolors
# Type: Package
# Title: Colors Palettes for R and 'ggplot2', Additional Themes for 'ggplot2'
# Version: 0.0.4
# Authors@R: c(person("Jared", "Huling", role = c("aut", "cre"), email = "jaredhuling@gmail.com", comment = c(ORCID = "0000-0003-0670-4845")))
# Description: Contains a selection of color palettes and 'ggplot2' themes designed by the package author.
# URL: https://jaredhuling.github.io/jcolors/
# BugReports: https://github.com/jaredhuling/jcolors/issues
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.2.0)
# Imports: grDevices, scales, ggplot2 (>= 3.0.0)
# RoxygenNote: 6.1.1
# Suggests: knitr, rmarkdown, gridExtra
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-05-22 03:35:38 UTC; huling.7
# Author: Jared Huling [aut, cre] (<https://orcid.org/0000-0003-0670-4845>)
# Maintainer: Jared Huling <jaredhuling@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-05-22 04:40:03 UTC
