{% set version = "0.0.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jcolors
  version: {{ version|replace("-", "_") }}

source:
  fn: jcolors_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/jcolors_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jcolors/jcolors_{{ version }}.tar.gz
  sha256: 26e686e30571682a637087af05ed7829b708eacf2ad33785efe183c83293b5a1

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-scales
  run:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-scales

test:
  commands:
    - $R -e "library('jcolors')"           # [not win]
    - "\"%R%\" -e \"library('jcolors')\""  # [win]

about:
  home: https://jaredhuling.github.io/jcolors/
  license: GPL-2
  summary: Contains a selection of color palettes and 'ggplot2' themes designed by the package
    author.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
